// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/fireworks.json" with { type: "json" };
import { flattenModelCatalog, type ModelCatalog } from "../model-catalog.ts";

type GeneratedModelGroups = {
	"anthropic-messages": {
		"accounts/fireworks/models/deepseek-v4-flash": object;
		"accounts/fireworks/models/deepseek-v4-pro": object;
		"accounts/fireworks/models/gpt-oss-120b": object;
		"accounts/fireworks/models/gpt-oss-20b": object;
		"accounts/fireworks/models/kimi-k2p6": object;
		"accounts/fireworks/models/kimi-k2p7-code": object;
		"accounts/fireworks/models/minimax-m2p7": object;
		"accounts/fireworks/models/minimax-m3": object;
		"accounts/fireworks/models/qwen3p7-plus": object;
		"accounts/fireworks/routers/kimi-k2p6-fast": object;
		"accounts/fireworks/routers/kimi-k2p6-turbo": object;
		"accounts/fireworks/routers/kimi-k2p7-code-fast": object;
	};
	"openai-completions": {
		"accounts/fireworks/models/glm-5p2": object;
		"accounts/fireworks/routers/glm-5p2-fast": object;
	};
};

const modelGroups = values as GeneratedModelGroups;

export const FIREWORKS_MODELS: ModelCatalog<typeof modelGroups, "fireworks"> =
	flattenModelCatalog("fireworks", modelGroups);
