// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/groq.json" with { type: "json" };
import { flattenModelCatalog, type ModelCatalog } from "../model-catalog.ts";

type GeneratedModelGroups = {
	"openai-completions": {
		"llama-3.1-8b-instant": object;
		"llama-3.3-70b-versatile": object;
		"meta-llama/llama-4-scout-17b-16e-instruct": object;
		"openai/gpt-oss-120b": object;
		"openai/gpt-oss-20b": object;
		"openai/gpt-oss-safeguard-20b": object;
		"qwen/qwen3-32b": object;
	};
};

const modelGroups = values as GeneratedModelGroups;

export const GROQ_MODELS: ModelCatalog<typeof modelGroups, "groq"> =
	flattenModelCatalog("groq", modelGroups);
