// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/minimax.json" with { type: "json" };
import { flattenModelCatalog, type ModelCatalog } from "../model-catalog.ts";

type GeneratedModelGroups = {
	"anthropic-messages": {
		"MiniMax-M2.7": object;
		"MiniMax-M2.7-highspeed": object;
		"MiniMax-M3": object;
	};
};

const modelGroups = values as GeneratedModelGroups;

export const MINIMAX_MODELS: ModelCatalog<typeof modelGroups, "minimax"> =
	flattenModelCatalog("minimax", modelGroups);
