// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/moonshotai.json" with { type: "json" };
import { flattenModelCatalog, type ModelCatalog } from "../model-catalog.ts";

type GeneratedModelGroups = {
	"openai-completions": {
		"kimi-k2-0711-preview": object;
		"kimi-k2-0905-preview": object;
		"kimi-k2-thinking": object;
		"kimi-k2-thinking-turbo": object;
		"kimi-k2-turbo-preview": object;
		"kimi-k2.5": object;
		"kimi-k2.6": object;
		"kimi-k2.7-code": object;
		"kimi-k2.7-code-highspeed": object;
		"kimi-k3": object;
	};
};

const modelGroups = values as GeneratedModelGroups;

export const MOONSHOTAI_MODELS: ModelCatalog<typeof modelGroups, "moonshotai"> =
	flattenModelCatalog("moonshotai", modelGroups);
