// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/nvidia.json" with { type: "json" };
import { flattenModelCatalog, type ModelCatalog } from "../model-catalog.ts";

type GeneratedModelGroups = {
	"openai-completions": {
		"google/gemma-3-12b-it": object;
		"google/gemma-3-4b-it": object;
		"meta/llama-3.1-70b-instruct": object;
		"meta/llama-3.1-8b-instruct": object;
		"meta/llama-3.2-11b-vision-instruct": object;
		"meta/llama-3.2-90b-vision-instruct": object;
		"meta/llama-3.3-70b-instruct": object;
		"minimaxai/minimax-m3": object;
		"mistralai/mistral-7b-instruct-v0.3": object;
		"mistralai/mistral-medium-3.5-128b": object;
		"moonshotai/kimi-k2.6": object;
		"nvidia/cosmos-reason2-8b": object;
		"nvidia/llama-3.1-nemotron-70b-instruct": object;
		"nvidia/llama-3.1-nemotron-nano-8b-v1": object;
		"nvidia/llama-3.1-nemotron-nano-vl-8b-v1": object;
		"nvidia/llama-3.1-nemotron-ultra-253b-v1": object;
		"nvidia/llama-3.3-nemotron-super-49b-v1": object;
		"nvidia/llama-3.3-nemotron-super-49b-v1.5": object;
		"nvidia/nemotron-3-nano-30b-a3b": object;
		"nvidia/nemotron-3-nano-omni-30b-a3b-reasoning": object;
		"nvidia/nemotron-3-super-120b-a12b": object;
		"nvidia/nemotron-3-ultra-550b-a55b": object;
		"nvidia/nemotron-nano-12b-v2-vl": object;
		"nvidia/nvidia-nemotron-nano-9b-v2": object;
		"openai/gpt-oss-120b": object;
		"openai/gpt-oss-20b": object;
		"poolside/laguna-xs-2.1": object;
		"stepfun-ai/step-3.7-flash": object;
		"thinkingmachines/inkling": object;
		"z-ai/glm-5.2": object;
	};
};

const modelGroups = values as GeneratedModelGroups;

export const NVIDIA_MODELS: ModelCatalog<typeof modelGroups, "nvidia"> =
	flattenModelCatalog("nvidia", modelGroups);
